CREATE TABLE users(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
age INT NOT NULL 
)

SELECT * FROM users
TRUNCATE TABLE users

INSERT INTO users VALUE(NULL,'詹姆斯',35);
INSERT INTO users VALUE(NULL,'戴维斯',27);
INSERT INTO users VALUE(NULL,'伦纳德',27);